server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true
    fetch-registry: true


spring:
  application:
    name: sociale-user-info
  flyway:
    baseline-on-migrate: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/db_sociale
    username: postgres
    password: postgres
  banner:
    image:
      location: classpath:banner.txt
  main:
    allow-bean-definition-overriding: true

sociale:
  security:
    token-secret-key: $0C14L3
    token-expiration-time: 36000

zuul:
  ribbon:
    ConnectTimeout: 120000
    ReadTimeout: 30000 

